// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9kN8XFj8u81hKYbh4A0JPvIW9B0Rl_9Y',
    appId: '1:380646549316:web:68a2e4b38a782ec89a9911',
    messagingSenderId: '380646549316',
    projectId: 'weatherinsider-bf5e8',
    authDomain: 'weatherinsider-bf5e8.firebaseapp.com',
    storageBucket: 'weatherinsider-bf5e8.appspot.com',
    measurementId: 'G-VWT5QPL57Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE8bQ4Kgv0-1OeAH04cC2b6AgOrEoZINo',
    appId: '1:380646549316:android:7539981fcd1ad6679a9911',
    messagingSenderId: '380646549316',
    projectId: 'weatherinsider-bf5e8',
    storageBucket: 'weatherinsider-bf5e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLxkd4ZetAKoOknETEB5_w6Jbu-s1ECQs',
    appId: '1:380646549316:ios:dfca5b1a7f38bf139a9911',
    messagingSenderId: '380646549316',
    projectId: 'weatherinsider-bf5e8',
    storageBucket: 'weatherinsider-bf5e8.appspot.com',
    iosBundleId: 'com.example.weatherinsider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLxkd4ZetAKoOknETEB5_w6Jbu-s1ECQs',
    appId: '1:380646549316:ios:dfca5b1a7f38bf139a9911',
    messagingSenderId: '380646549316',
    projectId: 'weatherinsider-bf5e8',
    storageBucket: 'weatherinsider-bf5e8.appspot.com',
    iosBundleId: 'com.example.weatherinsider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9kN8XFj8u81hKYbh4A0JPvIW9B0Rl_9Y',
    appId: '1:380646549316:web:1d24eddd7beee9a19a9911',
    messagingSenderId: '380646549316',
    projectId: 'weatherinsider-bf5e8',
    authDomain: 'weatherinsider-bf5e8.firebaseapp.com',
    storageBucket: 'weatherinsider-bf5e8.appspot.com',
    measurementId: 'G-WHK35ZTJ84',
  );
}
